services:
  - type: web
    name: astronomy-app
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: astronomy-app-db
          property: connectionString
    healthCheckPath: /api/health
    
databases:
  - name: astronomy-app-db
    databaseName: astronomy_app
    user: astronomy_user
    plan: starter